# Generated by Django 4.2.2 on 2023-11-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('based', '0007_alter_userdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
