# Generated by Django 4.2.2 on 2023-11-22 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('ur_id', models.AutoField(primary_key=True, serialize=False)),
                ('ur_role', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('ud_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(default=0)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='based.userrole')),
            ],
        ),
    ]
